### ISSUE TITLE
Does not support Subclipse 1.8

### ISSUE THREAD

**Issue by patrickcrocker** [tesla/m2eclipse-subclipse#3] opened 2011-10-19 21:10 UTC
The m2e-subclipse Team Provider does not support the new Subclipse 1.8 release.

m2e Marcketplace Installation error message:
Operation details
Cannot complete the install because one or more required items could not be found.
Software being installed: Maven SCM handler for Subclipse 0.13.0.201107071330 (org.sonatype.m2e.subclipse.feature.feature.group 0.13.0.201107071330)
Missing requirement: Maven SCM Handler for Subclipse 0.13.0.201107071330 (org.sonatype.m2e.subclipse 0.13.0.201107071330) requires 'bundle org.tigris.subversion.subclipse.core [1.6.0,1.7.0)' but it could not be found
Cannot satisfy dependency:
From: Maven SCM handler for Subclipse 0.13.0.201107071330 (org.sonatype.m2e.subclipse.feature.feature.group 0.13.0.201107071330)
To: org.sonatype.m2e.subclipse [0.13.0.201107071330]

**Comment by ifedorenko** [comment] 2011-10-19 22:14
we don't use subversion any more, so this will be WONTFIX unless somebody provides a quality patch.

**Comment by cysun** [comment] 2011-11-21 03:11
> we don't use subversion any more, so this will be WONTFIX unless somebody provides a quality patch.

Does this mean m2e-subversive won't support newer versions of Subversion either?

**Comment by apogrebnyak** [comment] 2011-12-07 18:46
ifedorenko wrote

> we don't use subversion any more, so this will be WONTFIX unless somebody provides a quality patch.

Looks like somebody did: https://github.com/sonatype/m2eclipse-subclipse/pull/4

Plus, if it's no longer supported, shouldn't it be removed from **m2e Marketpalce**?

**Comment by moldowan** [comment] 2011-12-08 18:01
Please apply the above mentioned patch!

My company just upgraded to SVN 1.7 which needs subclipse 1.8 and now I cannot use Eclipse to commit etc.

**Comment by apogrebnyak** [comment] 2011-12-08 18:17
@moldowan.  Actually, you don't need m2e-subclipse plugin at all to communicate with your repository.  This plugin is only needed if you ever want to materialize maven project from artifact descriptor.

If you want to upgrade to Subclipse 1.8.x, just uninstall m2e-subclipse plugin and you will be good to go. BTW, it would be a good idea to uninstall Subclipse 1.6.x at the same time as well, as it does not upgrade cleanly to 1.8 at all.

**Comment by moldowan** [comment] 2011-12-09 10:37
@apogrebnyak 
Thanks for the clarification. I was misled on how the integration actually works.
I needed to re-checkout the modules/projects and re-imported them to eclipse and now everything is fine (maven nature and svn overlay icons etc.).

**Comment by ghost** [comment] 2011-12-23 13:05
HI.  ifedorenko  . 
What is the meaning ???
But now we have projects in svn....

Error log: 
Operation details
Cannot complete the install because one or more required items could not be
found.
Software being installed: Maven SCM handler for Subclipse 0.13.0.201107071330
(org.sonatype.m2e.subclipse.feature.feature.group 0.13.0.201107071330)
Missing requirement: Maven SCM Handler for Subclipse 0.13.0.201107071330
(org.sonatype.m2e.subclipse 0.13.0.201107071330) requires 'bundle
org.tigris.subversion.subclipse.core [1.6.0,1.7.0)' but it could not be found
Cannot satisfy dependency:
From: Maven SCM handler for Subclipse 0.13.0.201107071330
(org.sonatype.m2e.subclipse.feature.feature.group 0.13.0.201107071330)
To: org.sonatype.m2e.subclipse [0.13.0.201107071330]

My env:
  Subclipse (Required)    1.8.4  
org.tigris.subversion.subclipse.feature.group    tigris.org
  Subversion Client Adapter (Required)    1.8.0  
org.tigris.subversion.clientadapter.feature.feature.group    tigris.org

Eclipse Java EE IDE for Web Developers.
Version: Indigo Service Release 1
Build id: 20110916-0149

TortoiseSVN 1.7.1, Build 22161 - 64 Bit , 2011/10/21 22:51:59
Subversion 1.7.1, 
apr 1.4.5
apr-utils 1.3.12
neon 0.29.6
OpenSSL 1.0.0e 6 Sep 2011
zlib 1.2.5

**Comment by LosD** [comment] 2011-12-23 20:50
> we don't use subversion any more, so this will be WONTFIX unless somebody provides a quality patch.

Then I guess you will make sure to remove the Sonatype video from http://eclipse.org/m2e/ about how amazing m2e works for materializing all kinds of projects from POMs, when you obviously won't maintain integration with one of the most used SCMs anymore...

**Comment by davispw** [comment] 2012-01-31 17:05
Since a patch has been offered, what is the status of this issue?

Funny how you can just decide to kill support for one of the most popular open-source source control systems.

**Comment by ghost** [comment] 2012-02-01 01:13
Kill old version  in MarketPlace , unsupported tools, not Subclipse.

2012/2/1 davispw <
reply@reply.github.com

**Comment by ifedorenko** [comment] 2012-02-01 16:57
We don't have the time/resources to maintain m2e/subversion integration and won't be able to review and apply the attached patch any time soon. m2e/subclipse integration is provided under EPL, I suggest you fork the project and distribute pre-built binaries yourself (and github makes this really easy to do).

**Closed as completed by ifedorenko** 2012-02-01 16:57 UTC

**Comment by apogrebnyak** [comment] 2012-02-01 18:27
@ifedorenko. Then remove it from m2e marketplace

**Comment by ghost** [comment] 2012-02-02 02:47
vote +1.

2012/2/2 apogrebnyak <
reply@reply.github.com

**Comment by ghost** [comment] 2012-02-02 02:47
or Add description about version

2012/2/2 zuxiong lin linzuxiong1988@gmail.com

**Comment by Clecompt** [comment] 2012-02-14 00:31
So that's it?  Closed?  Honestly, it's these sort of decisions that make Maven particularly difficult to adopt in any enterprise.  The materialize projects from SCM is a very useful feature and one used here internally.  I get that forking the project is an option but to have no centralized control over such an option is unacceptable.  So what's the path forward?  GIT I take it?

**Comment by LosD** [comment] 2012-02-15 09:07
Even worse: As m2e doesn't know about Subclipse anymore, it often gets confused when the POM is updated, i.e. by a switch.

This must be a bad joke.

**Comment by gniontas** [comment] 2012-06-28 04:46
In my 10 yrs of experience with java and many other open source technologies, I've never come across a statement like: 
"we don't use subversion any more, so this will be WONTFIX."

So, what do you use now ifedorenko? And what is the guarantee that you won't be "using" something else 5 months from now ?

**Comment by ifedorenko** [comment] 2012-06-28 10:48
Looks like you misunderstood the idea behind opensource. It is not about somebody else solving your problems for free. It is about users of software solving their problems themselves. You can press the "Fork" button at the top of this page to get you own personal copy of m2eclipse-subclipse codebase you can modify and maintain for as long as you want to.

**Comment by gniontas** [comment] 2012-06-29 06:38
We can have a never-ending discussion on the idea behind open source.. but I don't want to get into that. My statement above was two fold: First, I have NEVER seen that kind of statement from an open source contributor. Second was more of a question as to what will you be 'using' 5 months from now ?
If you read it right, I am not asking you to do anybody a favor. I am just questioning the credibility of your projects. Contributors like yourself are a liability to the spirit of open source ecosystem and thankfully... rare.

**Comment by RockyMM** [comment] 2012-06-29 13:29
@ifedorenko As we are on "idea behind opensource" - if there is strong community need for particular feature, you should not ignore it so lightly. You cannot view this feature request as a "problem". This is not a problem, but real community need which stopped few users in adopting m2e. I am sure that you are not developing m2e only for yourself?

At least if you are suggesting forking, please give us instructions how to publish our forked connector on m2e Marketplace.

**Comment by cysun** [comment] 2012-06-29 14:29
Mark Phippard from the Subclipse project has already created a fork at https://github.com/markphip/m2eclipse-subclipse. The Eclipse update site is at http://subclipse.tigris.org/m2eclipse/1.0. I've been using it with Subclipse 1.8.x for a while and it works perfectly.

BTW, I understand the users' frustration when an important project like this is discontinued, but the users should also understand that OSS authors don't own them anything. If you don't like a project, fork it or use some thing else.

**Comment by gniontas** [comment] 2012-06-29 19:39
Thank you cysun for the update. But I disagree on your 2nd point. If you don't like a project, don't just 'click' on the fork 
button and hack together a patch that works till next month. I am making a larger point here because these kinds of adhoc forks and short term solutions do nothing but pollute the ecosystem and waste people's time. There has to be some minimum level of quality and commitment to support a solution that you are putting in front of the community. If you cannot support it credibly, then hack together a repository in your closet and host it there to your friends' amusement.
Seriously, why do I have to deal with an m2e plugin, then a subclipse plugin and then an "m2e-subclipse connector" and 20 other adapters and their versions, only to land on this page to hear: "we don't use subversion any more, so this will be WONTFIX"
So, please if you can't provide some level of quality and can't maintain it responsibly, DON'T FORK IT!

**Comment by davispw** [comment] 2012-06-29 19:58
Linus Torvalds probably doesn't use 90% of the drivers in the linux kernel but as the project maintainer, when someone submits a working patch that will benefit the community, he accepts their patches.  That's what maintainers do.  They maintain.  There was a trivial pull request over 7 months ago -- just update the version numbers, really -- so if you're not going to accept patches, then cut this project loose and stop claiming to support it.

@ifedorenko you're not talking about a fork, you're talking about transferring ownership, so call it what it is.

**Comment by RockyMM** [comment] 2012-06-30 21:46
@cysun I've found out about Tigris' update site only half an hour after I've written my post. I think that we will be seeing less comments here on this issue report after you've posted the update site here.

Still, on your second point, I agree wholeheartedly with @gniontas and @davispw. As one wise man had said - at least we can agree to disagree - we have different views on open source. Maybe Apache has spoiled us - who knows, but when I think about OS, I generally think at what Apache does (and similarly to an extent Atlassian, Google, Mozilla and many more others). The type of treatment that Sonatype gives to community is as valid as Apache's but very strange to me.

**Comment by patrickcrocker** [comment] 2012-07-02 02:48
I'm really excited to know that Mark Phippard has forked this project.  Mark is one of the project administrators of the CollabNet Subversion Edge server.  I've posted several times to the CollabNet Subversion Admins forum and Mark has always responded within hours of my post (always with the answer to my question).

**Comment by SteveGillam** [comment] 2012-10-25 10:01
Arrived here whilst investigating Maven(3.0)/Eclipse(Juno))/Subversion(1.8) facet patterns - and found the above quite sad.
As I understand it Sonatype is an organisation and, whilst serving a community, is not itself a community. It provides m2e (v.grateful), m2e.scm (good), m2e.scm.svn (great), m2e.scm.svn.subclipse (brilliant - but only up to v1.7). v1.8 support is a feature request (not a bug if omitted - they don't 'have' to). Would be nice if their development workflow supported 'external' responsibilities (eg. if Mark wanted to take it on) but surely we can understand a corporate organisation not being able to open itself up in that way.
Yes, the issue 'resolution' may been more sympathetically handled but, in their defense, these guys have a job to do. So, if we want m2e.scm.svn.subclipse.18+ we just say thanks for what we do have and go look elsewhere (as I'm about to as, unfortunately, Mark's patch here isn't Juno).

**Comment by markphip** [comment] 2012-10-25 13:58
I posted a new build to the update site that removes the m2e version constraint.  From what I can see it works with 1.2.

**Comment by markphip** [comment] 2012-10-25 14:05
Just one other comment.  The changes that were committed to this project seem to already have relaxed the Subclipse version requirement to include 1.8.x.  So the version of the connector that m2eclipse publishes ought to work.  Maybe the problem is just with the people that installed the version I had posted since it has a higher version number and did not support 1.2?  If that is the case, you ought to be able to uninstall the version I posted (or install the newest version I just posted) and instead install the one that m2eclipse publishes.

While they might not plan to enhance this connector in the future, it does seem like they relaxed the version constraint so that it works with Subclipse 1.8

**Comment by markphip** [comment] 2012-10-25 17:09
Just to followup on the last comment, I uninstalled the version of the connector that I just published.  I then went to the m2e discovery site and it installed the Subclipse connector fine.  So it looks to me like Sonatype is publishing a connector that will work with Subclipse 1.8 and m2e 1.2.  If you previously installed the plugin I posted as a workaround, you just need to uninstall it so that you can get the one that Sonatype published.

**Comment by SteveGillam** [comment] 2012-10-25 18:41
Mark ******
